import { pick, randInt } from '../helpers';
import type { HeadlineGenerator } from '../types';
import { GENERIC_REALITIES } from '../wordPools';

// ── WEATHER/FILLER generators ──

export const weatherFillerGenerators: HeadlineGenerator[] = [
  () => ({
    headline: `WEATHER FORECAST: ${pick(['GREY', 'OVERCAST', 'CONCRETE-COLORED', 'IDEOLOGICALLY NEUTRAL'])} WITH ${pick(['PERIODIC GREY', 'SCATTERED GREYNESS', 'A CHANCE OF DARKER GREY', 'CONTINUED ABSENCE OF SUN'])}`,
    subtext: `Extended forecast: ${pick(['more of the same', 'similar but colder', 'grey with a chance of grey', 'the usual'])}. Week ahead: classified.`,
    reality: 'The meteorologist quit. The forecast is now generated by a dart board.',
    category: 'weather',
  }),

  () => ({
    headline: `WINTER ARRIVES ${pick(['ON SCHEDULE', 'AS PREDICTED', 'PER FIVE-YEAR WEATHER PLAN', 'AHEAD OF SCHEDULE (A TRIUMPH)'])}`,
    subtext: `Temperature: -${randInt(15, 45)} degrees. Status: ${pick(['brisk', 'refreshing', 'character-building', 'invigorating', 'survivable'])}`,
    reality: 'Winter arrived in August. The calendar has been amended.',
    category: 'weather',
  }),

  () => ({
    headline: `SPRING PREDICTED FOR ${pick(['NEXT MONTH', 'SOMETIME THIS YEAR', 'THE FORESEEABLE FUTURE', 'EVENTUALLY', 'SOON (REDEFINED)'])}`,
    subtext: 'Citizens advised to remain patient. Patience supplies: adequate.',
    reality:
      'Last spring lasted 2 days. A citizen blinked and missed it. He was counseled for inattention.',
    category: 'weather',
  }),

  () => ({
    headline: `SUN SPOTTED FOR ${randInt(3, 45)} MINUTES. CITIZENS CELEBRATE`,
    subtext: `Solar Committee confirms: this was a planned appearance. The sun is a party member in good standing.`,
    reality: 'It was a searchlight from the border patrol. Citizens celebrated anyway.',
    category: 'weather',
  }),

  // Absurdist filler
  () => ({
    headline: `EDITORIAL: ${pick(['NOTHING HAPPENED TODAY AND THAT IS GOOD', 'EVERYTHING IS FINE (REPEAT UNTIL TRUE)', 'THE STATE OF THE STATE: STATED', 'WHY YESTERDAY WAS THE BEST YESTERDAY YET', 'IN DEFENSE OF CONCRETE: A MANIFESTO'])}`,
    subtext: pick([
      'By the Editor (writing voluntarily, under observation).',
      'Opinions expressed are the only opinions.',
      'Reader feedback: not accepted.',
      'Corrections: there are none. There never are.',
    ]),
    reality: pick(GENERIC_REALITIES),
    category: 'editorial',
  }),

  () => ({
    headline: `CORRECTION: ${pick([
      'YESTERDAY\'S "EXPLOSION" WAS A "PLANNED ACOUSTIC EVENT"',
      'THE "MISSING BUILDING" WAS "RELOCATED FOR STRATEGIC REASONS"',
      'THE "FOOD SHORTAGE" IS A "CALORIC OPPORTUNITY"',
      'THE "POWER OUTAGE" WAS "VOLUNTARY DARKNESS"',
      'THE "CRUMBLING INFRASTRUCTURE" IS "ADAPTIVE ARCHITECTURE"',
      'THE "RAT INFESTATION" IS A "WILDLIFE INTEGRATION PROGRAM"',
      'THE "EMPTY SHELVES" REPRESENT "MINIMALIST RETAIL DESIGN"',
    ])}`,
    subtext: 'Pravda regrets the earlier understatement of how good things are.',
    reality: 'The original report was accurate. The correction is the fiction.',
    category: 'editorial',
  }),

  // Classified ads
  () => ({
    headline: `CLASSIFIED: ${pick([
      `SEEKING ${randInt(50, 500)} VOLUNTEERS FOR "SPECIAL PROJECT." SHOVELS PROVIDED`,
      `LOST: 1 BUILDING. LAST SEEN: STANDING. IF FOUND, CONTACT MINISTRY`,
      `FOR SALE: SLIGHTLY USED TRACTOR. CONDITION: THEORETICAL`,
      `WANTED: CITIZENS WHO CAN SMILE ON COMMAND. COMPETITIVE PAY (IN POTATOES)`,
      `FOUND: ${randInt(3, 30)} LEFT BOOTS. OWNERS PLEASE CLAIM AT WAREHOUSE 7`,
      `SEEKING QUALIFIED PLUMBER. QUALIFICATIONS: ALIVE, WILLING`,
      `FOR TRADE: 1 POTATO FOR 3 POEMS ABOUT TRACTORS. SERIOUS OFFERS ONLY`,
    ])}`,
    subtext:
      'All classified ads reviewed and approved by the Ministry of Commerce (dissolved 1976).',
    reality:
      'The classified section is the only honest part of the newspaper. This concerns everyone.',
    category: 'editorial',
  }),

  // Horoscope
  () => ({
    headline: `DAILY HOROSCOPE: ALL SIGNS PREDICT ${pick(['INCREASED PRODUCTIVITY', 'FAVORABLE QUOTA FULFILLMENT', 'LOYALTY TO THE STATE', 'CONCRETE', 'ANOTHER DAY', 'THE SAME AS YESTERDAY'])}`,
    subtext: `Astrology is bourgeois superstition. This horoscope is scientific socialist prediction.`,
    reality:
      'Horoscope written by the same person who writes the weather forecast. He is also the janitor.',
    category: 'editorial',
  }),

  // Year-in-review / seasonal reference
  (gs) => ({
    headline: `${gs.date.year} ON TRACK TO BE BEST YEAR IN SOVIET HISTORY`,
    subtext: `Previous best year: ${gs.date.year - 1}. Before that: ${gs.date.year - 2}. Pattern: every year is the best.`,
    reality: `${gs.date.year} is indistinguishable from ${gs.date.year - 1}. This is considered a success.`,
    category: 'editorial',
  }),
];
