name: Setup Node + pnpm
description: Setup Node.js and install dependencies with pnpm

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: "22"
  install:
    description: Whether to install dependencies
    required: false
    default: "true"
  install-args:
    description: Extra arguments for pnpm install
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: pnpm install ${{ inputs.install-args }}
