name: Setup Node + pnpm
description: Setup Node (from .nvmrc), pnpm (from packageManager), and install deps

inputs:
  node-version-file:
    description: Path to a Node version file (e.g. .nvmrc)
    required: false
    default: .nvmrc
  install:
    description: Whether to run pnpm install
    required: false
    default: "true"
  install-args:
    description: Arguments for pnpm install
    required: false
    default: "--frozen-lockfile"

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@9fd676a19091d4595eefd76e4bd31c97133911f1 # v4.2.0
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: pnpm

    - name: Install dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      env:
        INSTALL_ARGS: ${{ inputs.install-args }}
      run: pnpm install $INSTALL_ARGS
