// ─────────────────────────────────────────────────────────
//  WORD POOLS
//
//  Each pool is a set of interchangeable fragments that
//  plug into template slots. Combinatorial explosion
//  ensures near-infinite unique headlines.
// ─────────────────────────────────────────────────────────

// -- SUBJECTS: who the headline is about --

export const HERO_SUBJECTS = [
  'HEROIC WORKERS',
  'TIRELESS LABORERS',
  'DEDICATED COMRADES',
  'SELFLESS PROLETARIANS',
  'COURAGEOUS MINERS',
  'PATRIOTIC FARMERS',
  'VIGILANT CITIZENS',
  'REVOLUTIONARY YOUTH',
  'LOYAL PARTY MEMBERS',
  'IRON-WILLED BUILDERS',
  'PEOPLES MILITIA',
  'GLORIOUS FACTORY WORKERS',
  'VOLUNTEER BRIGADES',
  'MODEL CITIZENS',
  'SOCIALIST HEROES',
] as const;

export const ENEMY_SUBJECTS = [
  'CIA OPERATIVES',
  'NATO PROVOCATEURS',
  'WALL STREET BANKERS',
  'WESTERN SPIES',
  'CAPITALIST SABOTEURS',
  'IMPERIALIST AGENTS',
  'BOURGEOIS INFILTRATORS',
  'FOREIGN AGITATORS',
  'DECADENT OLIGARCHS',
  'REACTIONARY ELEMENTS',
  'TROTSKYIST WRECKERS',
  'COSMOPOLITAN SUBVERSIVES',
  'PENTAGON WARMONGERS',
  'BRITISH INTELLIGENCE',
  'WEST GERMAN PROVOCATEURS',
  'AMERICAN PROPAGANDISTS',
  'COUNTER-REVOLUTIONARY BANDITS',
  'ZIONIST CONSPIRATORS',
] as const;

export const INSTITUTIONS = [
  'THE PARTY',
  'THE CENTRAL COMMITTEE',
  'THE POLITBURO',
  'THE PEOPLES COUNCIL',
  'THE MINISTRY OF PRODUCTION',
  'THE MINISTRY OF TRUTH',
  'THE MINISTRY OF PLENTY',
  'THE PLANNING COMMISSION',
  'THE KGB',
  'THE SUPREME SOVIET',
  'THE ACADEMY OF SCIENCES',
  'THE WORKERS SOVIET',
  'THE YOUTH LEAGUE',
  'THE TRADE UNION',
  'THE COLLECTIVE FARM BUREAU',
] as const;

export const LEADER_TITLES = [
  'COMRADE GENERAL SECRETARY',
  'THE BRILLIANT CHAIRMAN',
  'OUR BELOVED LEADER',
  'THE PEOPLES FATHER',
  'THE GREAT HELMSMAN',
  'COMRADE FIRST SECRETARY',
  'THE WISE PREMIER',
  'THE TIRELESS NAVIGATOR',
  'DEAR COMRADE DIRECTOR',
  'THE SUPREME GUIDE',
  'THE ARCHITECT OF PROGRESS',
  'THE IRON GUARDIAN',
] as const;

// -- VERBS: what they did --

export const TRIUMPH_VERBS = [
  'EXCEEDED',
  'SURPASSED',
  'OBLITERATED',
  'SHATTERED',
  'DEMOLISHED',
  'ANNIHILATED',
  'CRUSHED',
  'ACHIEVED',
  'FULFILLED',
  'OVERFULFILLED',
  'COMPLETED',
  'ACCOMPLISHED',
  'DOUBLED',
  'TRIPLED',
  'QUADRUPLED',
] as const;

export const THREAT_VERBS = [
  'FOILED',
  'THWARTED',
  'EXPOSED',
  'UNMASKED',
  'NEUTRALIZED',
  'INTERCEPTED',
  'DEFEATED',
  'REPELLED',
  'CRUSHED',
  'LIQUIDATED',
  'ROUTED',
  'DISMANTLED',
] as const;

export const POSITIVE_VERBS = [
  'CELEBRATED',
  'HONORED',
  'DEMONSTRATED',
  'PROVED',
  'VOLUNTEERED FOR',
  'EMBRACED',
  'RALLIED BEHIND',
  'UNANIMOUSLY ENDORSED',
  'DEVOTED THEMSELVES TO',
  'RENEWED COMMITMENT TO',
] as const;

// -- OBJECTS: what was accomplished/threatened --

export const PRODUCTION_OBJECTS = [
  'PRODUCTION QUOTA',
  'FIVE-YEAR PLAN TARGET',
  'OUTPUT RECORD',
  'HARVEST BENCHMARK',
  'INDUSTRIAL MILESTONE',
  'EFFICIENCY STANDARD',
  'LABOR PRODUCTIVITY GOAL',
  'STEEL OUTPUT TARGET',
  'CONCRETE PRODUCTION NORM',
  'TRACTOR ASSEMBLY QUOTA',
  'COAL EXTRACTION RECORD',
  'GRAIN DELIVERY SCHEDULE',
  'VODKA DISTILLATION BENCHMARK',
  'BOOT MANUFACTURING TARGET',
  'TURNIP CULTIVATION QUOTA',
] as const;

export const THREAT_OBJECTS = [
  'SABOTAGE OPERATION',
  'ESPIONAGE RING',
  'DESTABILIZATION PLOT',
  'ECONOMIC WARFARE CAMPAIGN',
  'PROPAGANDA OFFENSIVE',
  'INFILTRATION ATTEMPT',
  'SMUGGLING NETWORK',
  'SUBVERSION SCHEME',
  'ASSASSINATION PLOT',
  'DISINFORMATION CAMPAIGN',
  'BIOLOGICAL WARFARE PROGRAM',
  'RADIO JAMMING OPERATION',
] as const;

export const CULTURAL_OBJECTS = [
  'REVOLUTIONARY SPIRIT',
  'SOCIALIST IDEALS',
  'COLLECTIVE HARMONY',
  'PROLETARIAN CULTURE',
  'PEOPLES UNITY',
  'WORKERS SOLIDARITY',
  'MARXIST-LENINIST PRINCIPLES',
  'DIALECTICAL PROGRESS',
  'CLASS CONSCIOUSNESS',
  'FRATERNAL COOPERATION',
] as const;

// -- QUALIFIERS: how it was done --

export const QUALIFIERS = [
  'AHEAD OF SCHEDULE',
  'UNDER BUDGET',
  'DESPITE CAPITALIST INTERFERENCE',
  'WITH REVOLUTIONARY FERVOR',
  'UNANIMOUSLY',
  'BY POPULAR DEMAND',
  'IN RECORD TIME',
  'WITH IRON DISCIPLINE',
  'THROUGH COLLECTIVE EFFORT',
  'THANKS TO WISE LEADERSHIP',
  'IN THE SPIRIT OF LENIN',
  'WITH BOUNDLESS ENTHUSIASM',
  "UNDER THE PARTY'S GUIDANCE",
  'IN FULFILLMENT OF SACRED DUTY',
  'WITH SELFLESS DEDICATION',
  'BEYOND ALL EXPECTATIONS',
  'TO THE GLORY OF THE MOTHERLAND',
  'IN DEFIANCE OF WESTERN DOUBT',
  'AS MARX PREDICTED',
  'AS THE FIVE-YEAR PLAN DEMANDS',
] as const;

// -- WESTERN FAILURES (for contrast) --

export const WESTERN_NOUNS = [
  'UNEMPLOYMENT',
  'INFLATION',
  'HOMELESSNESS',
  'STOCK MARKET CRASH',
  'BANK FAILURE',
  'CORRUPTION SCANDAL',
  'LABOR STRIKE',
  'RACE RIOT',
  'DRUG EPIDEMIC',
  'MORAL DECAY',
  'CONSUMER DEBT CRISIS',
  'HEALTHCARE COLLAPSE',
  'FACTORY CLOSURE',
  'BREAD LINE',
  'POVERTY RATE',
] as const;

export const WESTERN_COUNTRIES = [
  'AMERICA',
  'BRITAIN',
  'WEST GERMANY',
  'FRANCE',
  'JAPAN',
  'NATO',
  'THE WEST',
  'THE FREE WORLD',
  'WALL STREET',
  'THE PENTAGON',
  'WASHINGTON',
  'LONDON',
  'BONN',
] as const;

// -- SCIENTIFIC ACHIEVEMENTS (that don't exist) --

export const FAKE_DISCOVERIES = [
  'PERPETUAL MOTION TRACTOR',
  'COLD-RESISTANT WHEAT STRAIN',
  'TELEPATHIC CROP MONITORING',
  'NUCLEAR-POWERED SNOW PLOW',
  'CONCRETE THAT HEALS ITSELF',
  'VODKA-BASED ROCKET FUEL',
  'POTATO THAT GROWS IN DARKNESS',
  'INVISIBLE FENCE TECHNOLOGY',
  'ACOUSTIC WALL INSULATION FROM ANTHEM RECORDINGS',
  'IDEOLOGICALLY CORRECT WEATHER PREDICTION',
  'SOCIALIST-REALIST AI',
  'QUANTUM COLLECTIVE FARMING',
  'FASTER-THAN-LIGHT TELEGRAM',
  'SELF-HARVESTING TURNIP',
  'PROLETARIAN COLD FUSION',
  'DIALECTICAL MATERIALS SCIENCE',
] as const;

// -- SPORTS/COMPETITIONS --

export const SOVIET_SPORTS = [
  'WEIGHTLIFTING',
  'CHESS',
  'GYMNASTICS',
  'ICE HOCKEY',
  'FIGURE SKATING',
  'WRESTLING',
  'CROSS-COUNTRY SKIING',
  'SHOT PUT',
  'SYNCHRONIZED SWIMMING',
  'MARCHING',
  'POTATO PEELING',
  'QUEUE STANDING',
  'CONCRETE POURING',
  'SNOW SHOVELING',
  'DOCUMENT FILING',
] as const;

// -- EUPHEMISMS (for spinning bad situations) --

export const SHORTAGE_EUPHEMISMS = {
  food: [
    'VOLUNTARY CALORIC CONSERVATION PROGRAM',
    'CITIZENS ACHIEVE NEW INTERMITTENT FASTING RECORD',
    'DIETARY OPTIMIZATION INITIATIVE SUCCEEDS',
    'WEIGHT LOSS GOALS EXCEEDED ACROSS ALL SECTORS',
    'AGRICULTURAL OUTPUT REDIRECTED TO STRATEGIC RESERVES',
    'CITIZENS DEMONSTRATE DISCIPLINE IN EATING HABITS',
    'SURPLUS APPETITE REDIRECTED TO PRODUCTIVE LABOR',
  ] as const,
  money: [
    'VOLUNTARY AUSTERITY EMBRACED WITH ENTHUSIASM',
    'CITIZENS DONATE SAVINGS TO STATE DEVELOPMENT FUND',
    'MATERIAL POSSESSIONS DECLARED BOURGEOIS',
    'RUBLE ACHIEVES MAXIMUM THEORETICAL VALUE',
    'TREASURY INVESTS IN FUTURE GENERATIONS',
    'ECONOMIC MINIMALISM TREND SWEEPS NATION',
  ] as const,
  vodka: [
    'SOBRIETY INITIATIVE PROCEEDS AHEAD OF SCHEDULE',
    'CITIZENS DISCOVER JOY OF CLEAR-HEADED LABOR',
    'VODKA RESERVES STRATEGICALLY DEPLOYED TO FRONTLINES',
    'TEMPERANCE MOVEMENT ACHIEVES HISTORIC MILESTONE',
    'WORKERS PROVE ENTHUSIASM NEEDS NO CHEMICAL ASSISTANCE',
    'ANTI-ALCOHOL CAMPAIGN DECLARED OVERWHELMING SUCCESS',
  ] as const,
  power: [
    'SCHEDULED DARKNESS FOR ASTRONOMICAL OBSERVATION',
    'CANDLELIGHT APPRECIATION WEEK ENTERS MONTH FOUR',
    'ENERGY CONSERVATION AWARD WON BY ENTIRE CITY',
    'WORKERS EMBRACE DARKNESS, BOTH LITERAL AND METAPHORICAL',
    'POWER GRID UNDERGOES VOLUNTARY MEDITATION',
    'ELECTRICITY RATIONING BUILDS CHARACTER',
  ] as const,
  pop: [
    'POPULATION OPTIMIZED FOR MAXIMUM EFFICIENCY',
    'WORKFORCE STREAMLINED TO ELIMINATE REDUNDANCY',
    'CITIZENS VOLUNTEER FOR REMOTE AGRICULTURAL ASSIGNMENT',
    'DEMOGRAPHIC ADJUSTMENT COMPLETES ON SCHEDULE',
    'URBAN DENSITY TARGETS ACHIEVED THROUGH NATURAL MIGRATION',
    'POPULATION RIGHT-SIZED PER SCIENTIFIC CALCULATION',
  ] as const,
};

// -- BUILDING COLLAPSE / DESTRUCTION SPINS (used in contextual generators) --

export const DESTRUCTION_SPINS = [
  'URBAN RENEWAL ACCELERATES',
  'PLANNED DEMOLITION PROCEEDS FLAWLESSLY',
  'ARCHITECTURAL REFRESH INITIATIVE LAUNCHES',
  'CONSTRUCTION ZONE ESTABLISHED FOR BIGGER, BETTER BUILDING',
  'BUILDING VOLUNTARILY DISASSEMBLES FOR RECYCLING',
  'STRUCTURE RECLASSIFIED AS OPEN-AIR FACILITY',
  'INNOVATIVE DECONSTRUCTIVIST ARCHITECTURE DEBUTS',
  'RUBBLE REPURPOSED AS FOUNDATION FOR PROGRESS',
] as const;

// -- LEADER PRAISE FRAGMENTS --

export const LEADER_ACHIEVEMENTS = [
  'WORKS 18-HOUR DAYS',
  'PERSONALLY INSPECTS EVERY POTATO',
  'SLEEPS ONLY WHEN THE PEOPLE SLEEP (NEVER)',
  'READS 400 PAGES OF POLICY DAILY',
  'BENCH-PRESSES 200 KILOGRAMS',
  'WRITES POETRY BETWEEN MEETINGS',
  "HAS MEMORIZED EVERY CITIZEN'S NAME",
  'INVENTED A NEW TYPE OF CONCRETE',
  'PREDICTED THE WEATHER CORRECTLY ONCE',
  'NEGOTIATED FAVORABLE TREATY WITH WINTER',
  'SINGLE-HANDEDLY IMPROVED CROP YIELDS BY STARING AT FIELDS',
  'COMPOSED A SYMPHONY DURING LUNCH BREAK',
  'DESIGNED NEW TRACTOR WITH A PENCIL AND PURE WILLPOWER',
  'ACHIEVED ENLIGHTENMENT BUT REMAINED HUMBLE',
] as const;

export const LEADER_QUALITIES = [
  'INFINITE WISDOM',
  'UNMATCHED FORESIGHT',
  'LEGENDARY MODESTY',
  'SUPERHUMAN ENDURANCE',
  'DEEP CONCERN FOR THE MASSES',
  'IRON CONSTITUTION',
  'BRILLIANT STRATEGIC MIND',
  'FLAWLESS JUDGMENT',
  'INEXHAUSTIBLE PATIENCE',
  'RADIANT CHARISMA',
  'ENCYCLOPEDIC KNOWLEDGE',
  'UNWAVERING RESOLVE',
] as const;

export const NATURE_CREDITS = [
  'GOOD HARVEST ATTRIBUTED TO WISE AGRICULTURAL POLICY',
  "MILD WINTER CREDITED TO LEADER'S NEGOTIATIONS WITH NATURE",
  'SUNRISE OCCURS ON SCHEDULE THANKS TO PARTY PLANNING',
  'FAVORABLE WINDS BLOW IN DIRECTION OF SOCIALISM',
  'RAIN FALLS PRECISELY ON COLLECTIVE FARMS AS DIRECTED',
  'BIRDS RETURN FROM MIGRATION IN ORDERLY FORMATION',
  'RIVERS FLOW MORE EFFICIENTLY UNDER NEW MANAGEMENT',
  'MOUNTAINS STAND TALLER IN SOLIDARITY WITH THE PEOPLE',
] as const;

// -- REALITY FRAGMENTS (the truth behind the spin) --

export const GENERIC_REALITIES = [
  'Source: a clipboard found in a ditch.',
  'Investigation ongoing. Investigator also missing.',
  'Witnesses report seeing nothing. Twice.',
  'Documents confirming this were printed, then eaten.',
  'Statistics verified by the Department of Optimistic Counting.',
  'Three people were asked. Two agreed. The third was reassigned.',
  'The report was written in pencil so it can be corrected later.',
  'A committee has been formed to celebrate this. The committee has also been dissolved.',
  'This information is correct. Incorrectness has been made illegal.',
  'All citizens surveyed responded favorably. Non-favorable citizens were not surveyed.',
  'The numbers are real. Reality has been adjusted to match.',
  'Confirmed by an expert who preferred to remain employed.',
  'This fact has been verified by the Ministry of Facts, which also verified itself.',
  'Any resemblance to actual events is purely ideological.',
] as const;

export const THREAT_REALITIES = [
  'The "spy" was a confused tourist with a camera.',
  'The "saboteur" was a pigeon that shorted a transformer.',
  'The "plot" was reconstructed from a torn napkin doodle.',
  'Intelligence sources: a man who talks to pigeons.',
  'Evidence: one (1) suspicious-looking hat.',
  'The "agent" was a radio picking up Polish folk music.',
  'Threat level determined by drawing lots.',
  'The "infiltrator" turned out to be a lost plumber from Sector 3.',
  'CIA involvement confirmed by a ouija board in the KGB basement.',
  'NATO detected using a compass that only points east.',
] as const;
