/**
 * @module game/economy/types
 *
 * All type definitions for the planned economy system.
 */

// ─────────────────────────────────────────────────────────────────────────────
//  Extended Resources
// ─────────────────────────────────────────────────────────────────────────────

/** Extended resources beyond the base money/food/vodka/power. */
export interface ExtendedResources {
  /** From forest clearing, used for heating + construction */
  timber: number;
  /** From factories, used for construction + upgrades */
  steel: number;
  /** Generated by ministries, consumed by everything. The lifeblood of bureaucracy. */
  paperwork: number;
}

/** The base resources that already exist in the ECS. */
export interface BaseResources {
  money: number;
  food: number;
  vodka: number;
  power: number;
  powerUsed: number;
  population: number;
}

/** Combined resource set for calculations that span both base and extended. */
export type AllResources = BaseResources & ExtendedResources;

/** Transferable resource keys — resources that can be allocated / delivered. */
export type TransferableResource = 'food' | 'vodka' | 'money' | 'steel' | 'timber';

// ─────────────────────────────────────────────────────────────────────────────
//  Trudodni (Labor Units)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Trudodni — "labor-day" accounting.
 *
 * In the real kolkhoz system, trudodni were essentially IOUs for work
 * performed. Workers who didn't hit their minimums received less food.
 * A system designed to incentivize productivity that mostly incentivized
 * creative bookkeeping.
 */
export interface TrudodniRecord {
  /** Total labor-days contributed this plan period */
  totalContributed: number;
  /** Labor-days per building (keyed by grid position "x,y") */
  perBuilding: Map<string, number>;
  /** Minimum trudodni required to receive full rations */
  minimumRequired: number;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Fondy (State Allocations)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fondy — centrally planned resource allocations.
 *
 * The state allocates resources to your settlement on a schedule.
 * Delivery is unreliable — what arrives may be less than promised,
 * late, or occasionally nothing at all. Reliability degrades in
 * later eras as the system slowly collapses under its own weight.
 */
export interface FondyAllocation {
  /** Resources allocated by central planning */
  allocated: Record<TransferableResource, number>;
  /** Resources actually delivered (always <= allocated, often much less) */
  delivered: Record<TransferableResource, number>;
  /** Ticks until next delivery */
  nextDeliveryTick: number;
  /** Delivery interval in ticks */
  deliveryInterval: number;
  /** Reliability factor (0-1, how much of allocated actually arrives) */
  reliability: number;
}

/** Result of a single fondy delivery attempt. */
export interface FondyDeliveryResult {
  /** What was promised */
  allocated: Record<TransferableResource, number>;
  /** What actually showed up */
  actualDelivered: Record<TransferableResource, number>;
  /** Whether the delivery happened at all */
  delivered: boolean;
  /** Descriptive reason if delivery failed or was partial */
  reason: string;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Blat (Connections)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Blat — the unofficial economy of favors and connections.
 *
 * "It's not what you know, it's who you know" — except in the USSR
 * this was literally how goods moved. Blat greases the wheels that
 * central planning forgot to oil.
 */
export interface BlatState {
  /** Hidden influence currency (0-100) */
  connections: number;
  /** Cumulative blat spent over the game */
  totalSpent: number;
  /** Cumulative blat earned over the game */
  totalEarned: number;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Ration Cards
// ─────────────────────────────────────────────────────────────────────────────

/** Citizen categories for ration distribution. */
export type RationTier = 'worker' | 'employee' | 'dependent' | 'child';

/**
 * Ration card system — active during crisis periods.
 *
 * Ration cards: 1929-1935, 1941-1947, 1983+.
 * Because nothing says "workers' paradise" like standing in line
 * with a little booklet that determines how much bread you're
 * allowed to eat.
 */
export interface RationConfig {
  /** Whether ration cards are currently active */
  active: boolean;
  /** Ration amounts per tier per tick */
  rations: Record<RationTier, { food: number; vodka: number }>;
}

/** Ration demand calculation result. */
export interface RationDemand {
  food: number;
  vodka: number;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Production Chains
// ─────────────────────────────────────────────────────────────────────────────

/** A multi-step production chain transforming raw inputs into outputs. */
export interface ProductionChain {
  id: string;
  name: string;
  steps: ProductionStep[];
}

/** A single step in a production chain. */
export interface ProductionStep {
  /** defId of building that performs this step */
  building: string;
  /** resource -> amount consumed */
  input: Record<string, number>;
  /** resource -> amount produced */
  output: Record<string, number>;
  /** Number of ticks this step requires */
  ticksRequired: number;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Stakhanovite Events
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Stakhanovite event — a worker dramatically exceeds their quota.
 *
 * Named after Alexei Stakhanov, who allegedly mined 102 tonnes of coal
 * in a single shift (he had help, but Pravda omitted that detail).
 * The irony: celebrating one worker's achievement raises the quota
 * for everyone else. Hooray.
 */
export interface StakhanoviteEvent {
  /** The heroic worker's name */
  workerName: string;
  /** Building where the feat occurred */
  building: string;
  /** Production boost as a multiplier (e.g. 2.5 = 250% of normal) */
  productionBoost: number;
  /** Propaganda value generated (affects blat and morale) */
  propagandaValue: number;
  /** The new quota target increase caused by this achievement */
  quotaIncrease: number;
  /** Pravda-style announcement text */
  announcement: string;
}

// ─────────────────────────────────────────────────────────────────────────────
//  MTS (Machine-Tractor Stations)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * MTS — Machine-Tractor Stations (1922-1958).
 *
 * The state owned the tractors, and kolkhozes rented them.
 * Because collective farmers couldn't be trusted with heavy machinery —
 * or perhaps because owning the means of production is only for the state
 * that claims to represent the workers who use them.
 *
 * Active only during the MTS era. Boosts kolkhoz grain output at a ruble cost.
 * After 1958 (Khrushchev's reform), kolkhozes buy their own equipment.
 */
export interface MTSState {
  /** Whether MTS stations are active (year-dependent) */
  active: boolean;
  /** Number of tractor units available */
  tractorUnits: number;
  /** Cost per tractor unit per tick (in rubles) */
  rentalCostPerUnit: number;
  /** Grain production multiplier when MTS is active and paid for */
  grainBoostMultiplier: number;
  /** Total rubles spent on MTS rental this plan period */
  totalRentalSpent: number;
}

/** Result of MTS processing for one tick. */
export interface MTSTickResult {
  /** Whether MTS was active and applied */
  applied: boolean;
  /** Rubles charged this tick */
  cost: number;
  /** Grain production multiplier applied */
  grainMultiplier: number;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Heating Progression
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Heating tier — progression from primitive to (theoretically) modern.
 *
 * - pechka: Wood-burning stove. Cheap, reliable, consumes timber.
 * - district: Centralized coal/power heating. Efficient when working.
 *   Prone to catastrophic failure because Soviet infrastructure.
 * - crumbling: What district heating becomes after decades of deferred
 *   maintenance. Still requires power, barely functions.
 */
export type HeatingTier = 'pechka' | 'district' | 'crumbling';

export interface HeatingState {
  /** Current heating tier */
  tier: HeatingTier;
  /** Resource consumed per tick */
  consumption: { resource: 'timber' | 'power'; amount: number };
  /** Population capacity served by current heating */
  capacityServed: number;
  /** Efficiency (0-1): how much of the population is actually warm */
  efficiency: number;
  /** Ticks since last maintenance (district/crumbling only) */
  ticksSinceRepair: number;
  /** Whether heating is currently failing (winter death risk) */
  failing: boolean;
}

/** Result of heating system tick. */
export interface HeatingTickResult {
  /** Resource consumed */
  consumed: { resource: string; amount: number };
  /** Whether heating is operational */
  operational: boolean;
  /** Population at risk from cold (if heating fails in winter) */
  populationAtRisk: number;
  /** Whether a breakdown occurred this tick */
  breakdown: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Currency Reform
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Currency reform — the state's favorite way to "stabilize" the economy.
 *
 * Historical reforms: 1922-24, 1947, 1961, 1991.
 * Each reform converts old rubles to new rubles at an exchange rate
 * that conveniently reduces everyone's savings. The state assures
 * citizens this is for their benefit.
 */
export interface CurrencyReformEvent {
  /** Year the reform takes effect */
  year: number;
  /** Name of the reform */
  name: string;
  /** Exchange rate: old rubles per new ruble (e.g. 10 = 10:1 confiscation) */
  exchangeRate: number;
  /** Pravda-style announcement */
  announcement: string;
  /** Whether the reform has been applied */
  applied: boolean;
}

/** Result of applying a currency reform. */
export interface CurrencyReformResult {
  /** Reform that was applied */
  reform: CurrencyReformEvent;
  /** Money before reform */
  moneyBefore: number;
  /** Money after reform */
  moneyAfter: number;
  /** Amount "stabilized" (i.e., confiscated) */
  amountLost: number;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Difficulty Multipliers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Full difficulty multiplier set.
 *
 * Controls every aspect of economic punishment. Worker difficulty
 * is "this is fine." Tovarish difficulty is "the state has decided
 * you will not be fine."
 */
export interface DifficultyMultipliers {
  /** Quota target scaling (higher = harder quotas) */
  quotaTarget: number;
  /** Starting resources scaling (lower = fewer resources) */
  startingResources: number;
  /** Population birth rate multiplier */
  birthRate: number;
  /** Building decay rate multiplier (higher = faster decay) */
  decayRate: number;
  /** Number of politruks (political officers) per 100 citizens */
  politruksPer100: number;
  /** Fondy delivery reliability modifier (applied on top of era base) */
  fondyReliability: number;
  /** Compulsory delivery rate modifier (higher = more extraction) */
  deliveryRate: number;
  /** Event severity scaling (higher = worse events) */
  eventSeverity: number;
  /** Black mark decay interval multiplier (higher = slower decay) */
  markDecayRate: number;
  /** Starvation threshold modifier (higher = more citizens die) */
  starvationRate: number;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Difficulty & Eras
// ─────────────────────────────────────────────────────────────────────────────

export type DifficultyLevel = 'worker' | 'comrade' | 'tovarish';

export type EraId =
  | 'revolution'
  | 'industrialization'
  | 'wartime'
  | 'reconstruction'
  | 'thaw'
  | 'stagnation'
  | 'perestroika'
  | 'eternal';

// ─────────────────────────────────────────────────────────────────────────────
//  Economy Tick Results
// ─────────────────────────────────────────────────────────────────────────────

/** Result returned from each economy tick. */
export interface EconomyTickResult {
  /** Trudodni earned this tick */
  trudodniEarned: number;
  /** Whether a fondy delivery occurred */
  fondyDelivered: FondyDeliveryResult | null;
  /** Stakhanovite event if one fired */
  stakhanovite: StakhanoviteEvent | null;
  /** Current blat connections level */
  blatLevel: number;
  /** Whether rations are active */
  rationsActive: boolean;
  /** Ration demand this tick (if active) */
  rationDemand: RationDemand | null;
  /** MTS result if active */
  mtsResult: MTSTickResult | null;
  /** Heating result */
  heatingResult: HeatingTickResult | null;
  /** Currency reform if one triggered */
  currencyReform: CurrencyReformResult | null;
  /** Passive per-tick KGB risk from high blat level */
  blatKgbResult: { investigated: boolean; arrested: boolean; announcement: string | null } | null;
}

/** Remainder allocation after fondy deliveries — what's left for the people. */
export interface RemainderAllocation {
  /** Resources distributed to citizens */
  distributed: Record<TransferableResource, number>;
  /** Resources held in reserve (stockpile) */
  reserved: Record<TransferableResource, number>;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Serialization
// ─────────────────────────────────────────────────────────────────────────────

export interface EconomySaveData {
  trudodni: {
    totalContributed: number;
    perBuilding: Array<[string, number]>;
    minimumRequired: number;
  };
  fondy: {
    allocated: Record<TransferableResource, number>;
    delivered: Record<TransferableResource, number>;
    nextDeliveryTick: number;
    deliveryInterval: number;
    reliability: number;
  };
  blat: BlatState;
  rations: RationConfig;
  mts: MTSState;
  heating: HeatingState;
  currencyReforms: CurrencyReformEvent[];
  era: EraId;
  difficulty: DifficultyLevel;
}
