/**
 * buildingDefs.ts — Runtime access to generated building definitions.
 *
 * Loads the JSON generated by `scripts/generate_building_defs.ts`,
 * validates with Zod, and exports typed accessors for use by:
 *   - Canvas2DRenderer (sprite paths, anchors, footprints)
 *   - Miniplex ECS factories (building stats, renderable data)
 *   - Toolbar UI (names, icons, costs)
 *
 * The generated JSON is imported at build time via Vite's JSON import.
 */

// Vite handles JSON imports — this resolves at build time.
import generatedJson from './buildingDefs.generated.json';
import type {
  BuildingDef,
  BuildingDefsFile,
  Footprint,
  Role,
  SpriteData,
} from './buildingDefs.schema';
import { BuildingDefsFileSchema } from './buildingDefs.schema';

// ── Validate at module load ──────────────────────────────────────────────────

const parsed = BuildingDefsFileSchema.safeParse(generatedJson);
if (!parsed.success) {
  console.error('buildingDefs.generated.json failed Zod validation:', parsed.error.issues);
  throw new Error('Invalid building definitions — regenerate with `pnpm pipeline:defs`');
}

const data: BuildingDefsFile = parsed.data;

// ── Exports ──────────────────────────────────────────────────────────────────

/** All building definitions keyed by sprite ID. */
export const BUILDING_DEFS: Readonly<Record<string, BuildingDef>> = data.buildings;

/** Array of all building IDs. */
export const BUILDING_IDS: readonly string[] = Object.keys(data.buildings);

/** Get a building definition by sprite ID. Returns undefined if not found. */
export function getBuildingDef(id: string): BuildingDef | undefined {
  return data.buildings[id];
}

/** Get the sprite data for a building. */
export function getSpriteData(id: string): SpriteData | undefined {
  return data.buildings[id]?.sprite;
}

/** Get the grid footprint for a building. Defaults to 1×1 if unknown. */
export function getFootprint(id: string): Footprint {
  return data.buildings[id]?.footprint ?? { tilesX: 1, tilesY: 1 };
}

/** Get all building IDs for a given role. */
export function getBuildingsByRole(role: Role): string[] {
  return Object.entries(data.buildings)
    .filter(([, def]) => def.role === role)
    .map(([id]) => id);
}

/** Schema version of the loaded data. */
export const DEFS_VERSION = data.version;

// Re-export types for convenience
export type { BuildingDef, BuildingDefsFile, Footprint, Role, SpriteData };
